### ISSUE TITLE
Luarocks is broken

### ISSUE THREAD

**Issue by dru89** [iryont/lua-struct#20]
We noticed an issue when we were trying to install this module earlier today for one of our builds.

You can pretty simply reproduce it by just trying to install the luarock:

```
$ luarocks install lua-struct 0.9.0-1
Warning: falling back to wget - install luasec to get native HTTPS support
Installing https://luarocks.org/lua-struct-0.9.0-1.rockspec
Cloning into 'lua-struct'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), 4.29 KiB | 1.07 MiB/s, done.


Error: Failed copying struct.lua
```

Digging into this, it looks like y'all have been reorganizing the code for better maintenance, which is great! Unfortunately, though, if you look at [lua-struct](https://luarocks.org/modules/iryont/lua-struct) on luarocks.org, it:

* Only has version [0.9.0-1](https://luarocks.org/modules/iryont/lua-struct/0.9.0-1)
* And that [luarocks rockspec](https://luarocks.org/manifests/iryont/lua-struct-0.9.0-1.rockspec) just points to the `HEAD` of this repo, looking for `struct.lua` on the root level. 

Would it be possible to either:
* Publish a new version of `0.9.0-1` with the latest directory structure? (I'm not sure if LuaRocks will let you republish such an old version, though. It's a shame that old version doesn't have a tag associated with it lol.)
* Or publish the latest version of `0.9.2-1`?

**Comment by iryont** [comment]
Indeed, it is a shame. Anyway, I did upload new rockspec file with new version. Also, I think I managed to add tag to the older version (0.9.0), so it should work nonetheless.
