### ISSUE TITLE
Give `unpack` an optional start_pos

### ISSUE THREAD

**Issue by EnTerr** [iryont/lua-struct#7]
Again, i found myself in need of this feature from the original/C struct, so added it to my copy by a small modification:

``` lua
--function struct.unpack(format, stream)
--  local vars = {}
--  local iterator = 1
function struct.unpack(format, stream, start_pos)
  local vars = {}
  local iterator = start_pos or 1
```

(Btw, i find your code clean and very easy to work with)

**Comment by iryont** [comment]
Hey

I'm glad to hear that. Currently I do not have much time to work on it, but once I get some time I will implement your ideas.

**Comment by EnTerr** [comment]
Understood. I opened the items to note the changes i had to do to be able to use this as replacement of the C `struct` in my project
